#!/usr/bin/python3

from os import walk
from os.path import join as pjoin, getmtime as mtime, getctime as ctime
from subprocess import Popen
from shlex import split as sh_split

def main():
    git_dts = []
    git_log = Popen(sh_split('bash -c "git log --date=iso | cat"'))
    stdout, stderr = git_log.communicate()

    if stderr is not None or stdout is None:
        print(stderr)
        return

    for line in stdout:
        line = str(line).lower()
        if line.startswith("date"):
            date = line.split()[-2].strip()
            time = line.split()[-3].strip()

    os_dts = []

    def find_all_files(dirpath: str = "./"):
        acc = []
        for dirpath, dirnames, filenames in walk(dirpath):
            acc += [pjoin(dirpath, file) for file in filenames]
        return acc

    all_files = find_all_files()
    for file in all_files:
        os_dts.append(ctime(file))
        os_dts.append(mtime(file))


main()